# Generated by Django 3.2.7 on 2021-09-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shoe_size',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
