# Generated by Django 3.2.7 on 2021-09-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_shoe_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shoe_size',
            field=models.CharField(max_length=5, null=True, verbose_name='Размер стопы'),
        ),
    ]
